name: 'Create README.md file'
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  readme-create:
    uses: clouddrove/github-shared-workflows/.github/workflows/readme.yml@master
    secrets:
      TOKEN: ${{ secrets.GITHUB }}
      SLACK_WEBHOOK_TERRAFORM: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }}
